// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToyotaCars.Areas.Data;

#nullable disable

namespace ToyotaMarketplace.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260424032158_AddUserAndToyotaAdminSchema")]
    partial class AddUserAndToyotaAdminSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ToyotaMarketplace.Models.Users.ToyotaAdmin", b =>
                {
                    b.Property<int>("ToyotaAdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ToyotaAdminId"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ToyotaAdminId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ToyotaAdmins");
                });

            modelBuilder.Entity("ToyotaMarketplace.Models.Users.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserFirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ToyotaMarketplace.Models.Users.ToyotaAdmin", b =>
                {
                    b.HasOne("ToyotaMarketplace.Models.Users.User", "User")
                        .WithOne("ToyotaAdmin")
                        .HasForeignKey("ToyotaMarketplace.Models.Users.ToyotaAdmin", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ToyotaMarketplace.Models.Users.User", b =>
                {
                    b.Navigation("ToyotaAdmin")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
