// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToyotaMarketplace.Areas.Data;

#nullable disable

namespace ToyotaMarketplace.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260525051418_AddNavPropertyToTransmissionTypeInVehiclePerformanceTableAndVehicleSpecFKInVehicleTable")]
    partial class AddNavPropertyToTransmissionTypeInVehiclePerformanceTableAndVehicleSpecFKInVehicleTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ToyotaMarketplace.Models.Users.ToyotaAdmin", b =>
                {
                    b.Property<int>("ToyotaAdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ToyotaAdminId"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ToyotaAdminId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ToyotaAdmins");
                });

            modelBuilder.Entity("ToyotaMarketplace.Models.Users.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserFirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ToyotaMarketplace.Models.Vehicles.Specs.BatteryType", b =>
                {
                    b.Property<int>("BatteryTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BatteryTypeId"));

                    b.Property<string>("BatteryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BatteryTypeId");

                    b.ToTable("BatteryTypes");
                });

            modelBuilder.Entity("ToyotaMarketplace.Models.Vehicles.Specs.BrakeType", b =>
                {
                    b.Property<int>("BrakeTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BrakeTypeId"));

                    b.Property<string>("FrontBrake")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RearBrake")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BrakeTypeId");

                    b.ToTable("BrakeTypes");
                });

            modelBuilder.Entity("ToyotaMarketplace.Models.Vehicles.Specs.DriveMode", b =>
                {
                    b.Property<int>("DriveModeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DriveModeId"));

                    b.Property<string>("ModeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DriveModeId");

                    b.ToTable("DriveModes");
                });

            modelBuilder.Entity("ToyotaMarketplace.Models.Vehicles.Specs.FuelType", b =>
                {
                    b.Property<int>("FuelTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FuelTypeId"));

                    b.Property<string>("FuelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FuelTypeId");

                    b.ToTable("FuelTypes");
                });

            modelBuilder.Entity("ToyotaMarketplace.Models.Vehicles.Specs.PowerSteeringType", b =>
                {
                    b.Property<int>("PowerSteeringTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PowerSteeringTypeId"));

                    b.Property<string>("PowerSteeringTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PowerSteeringTypeId");

                    b.ToTable("PowerSteeringTypes");
                });

            modelBuilder.Entity("ToyotaMarketplace.Models.Vehicles.Specs.PowerTrain", b =>
                {
                    b.Property<int>("PowerTrainId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PowerTrainId"));

                    b.Property<string>("PowerTrainType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PowerTrainId");

                    b.ToTable("PowerTrains");
                });

            modelBuilder.Entity("ToyotaMarketplace.Models.Vehicles.Specs.SteeringSystem", b =>
                {
                    b.Property<int>("SteeringSystemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SteeringSystemId"));

                    b.Property<string>("SteeringSystemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SteeringSystemId");

                    b.ToTable("SteeringSystems");
                });

            modelBuilder.Entity("ToyotaMarketplace.Models.Vehicles.Specs.SteeringType", b =>
                {
                    b.Property<int>("SteeringTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SteeringTypeId"));

                    b.Property<string>("SteeringTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SteeringTypeId");

                    b.ToTable("SteeringTypes");
                });

            modelBuilder.Entity("ToyotaMarketplace.Models.Vehicles.Specs.TransmissionType", b =>
                {
                    b.Property<int>("TransmissionTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransmissionTypeId"));

                    b.Property<string>("TransmissionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TransmissionTypeId");

                    b.ToTable("TransmissionTypes");
                });

            modelBuilder.Entity("ToyotaMarketplace.Models.Vehicles.Specs.VehicleDimensionFuel", b =>
                {
                    b.Property<int>("DimensionFuelId")
                        .HasColumnType("int");

                    b.Property<float>("DimensionX")
                        .HasColumnType("real");

                    b.Property<float>("DimensionY")
                        .HasColumnType("real");

                    b.Property<float>("DimensionZ")
                        .HasColumnType("real");

                    b.Property<float>("FuelCapacity")
                        .HasColumnType("real");

                    b.Property<float>("GroundClearance")
                        .HasColumnType("real");

                    b.Property<float>("PayloadCapacity")
                        .HasColumnType("real");

                    b.Property<int>("SeatingCapacity")
                        .HasColumnType("int");

                    b.HasKey("DimensionFuelId");

                    b.ToTable("VehicleDimensionFuels");
                });

            modelBuilder.Entity("ToyotaMarketplace.Models.Vehicles.Specs.VehicleFeature", b =>
                {
                    b.Property<int>("FeatureId")
                        .HasColumnType("int");

                    b.Property<string>("Audio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Exterior")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Function")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ignition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Interior")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeterCluster")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MultiInfoDisplay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Safety")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TireDiskWheel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FeatureId");

                    b.ToTable("VehicleFeatures");
                });

            modelBuilder.Entity("ToyotaMarketplace.Models.Vehicles.Specs.VehiclePerformance", b =>
                {
                    b.Property<int>("PerformanceId")
                        .HasColumnType("int");

                    b.Property<string>("Chassis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Drivetrain")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Engine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TransmissionTypeId")
                        .HasColumnType("int");

                    b.HasKey("PerformanceId");

                    b.HasIndex("TransmissionTypeId");

                    b.ToTable("VehiclePerformances");
                });

            modelBuilder.Entity("ToyotaMarketplace.Models.Vehicles.Specs.VehiclePerformanceDriveMode", b =>
                {
                    b.Property<int>("PerformanceId")
                        .HasColumnType("int");

                    b.Property<int>("DriveModeId")
                        .HasColumnType("int");

                    b.HasKey("PerformanceId", "DriveModeId");

                    b.HasIndex("DriveModeId");

                    b.ToTable("VehiclePerformanceDriveModes");
                });

            modelBuilder.Entity("ToyotaMarketplace.Models.Vehicles.Specs.VehicleSpec", b =>
                {
                    b.Property<int>("VehicleSpecId")
                        .HasColumnType("int");

                    b.Property<int?>("DimensionFuelId")
                        .HasColumnType("int");

                    b.Property<string>("Disclaimer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FeatureId")
                        .HasColumnType("int");

                    b.Property<string>("ModelNote")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PerformanceId")
                        .HasColumnType("int");

                    b.Property<int?>("TechnicalId")
                        .HasColumnType("int");

                    b.HasKey("VehicleSpecId");

                    b.ToTable("VehicleSpecs");
                });

            modelBuilder.Entity("ToyotaMarketplace.Models.Vehicles.Specs.VehicleTechnical", b =>
                {
                    b.Property<int>("TechnicalId")
                        .HasColumnType("int");

                    b.Property<string>("AntiLockBrakeSystem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BatteryTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("BrakeTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("FuelTypeId")
                        .HasColumnType("int");

                    b.Property<float>("MinimumTurningRadius")
                        .HasColumnType("real");

                    b.Property<int?>("PowerSteeringTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("SteeringSystemId")
                        .HasColumnType("int");

                    b.Property<int?>("SteeringTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Suspension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TechnicalId");

                    b.HasIndex("BrakeTypeId");

                    b.HasIndex("FuelTypeId");

                    b.HasIndex("PowerSteeringTypeId");

                    b.HasIndex("SteeringSystemId");

                    b.HasIndex("SteeringTypeId");

                    b.ToTable("VehicleTechnicals");
                });

            modelBuilder.Entity("ToyotaMarketplace.Models.Vehicles.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleId"));

                    b.Property<DateTime>("DatePosted")
                        .HasColumnType("datetime2");

                    b.Property<int>("PowerTrainId")
                        .HasColumnType("int");

                    b.Property<int>("ToyotaAdminId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleColorId")
                        .HasColumnType("int");

                    b.Property<string>("VehicleImg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VehicleModelId")
                        .HasColumnType("int");

                    b.Property<string>("VehicleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VehicleSRP")
                        .HasColumnType("int");

                    b.Property<int>("VehicleSpecId")
                        .HasColumnType("int");

                    b.HasKey("VehicleId");

                    b.HasIndex("PowerTrainId");

                    b.HasIndex("ToyotaAdminId");

                    b.HasIndex("VehicleColorId");

                    b.HasIndex("VehicleModelId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("ToyotaMarketplace.Models.Vehicles.VehicleColor", b =>
                {
                    b.Property<int>("VehicleColorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleColorId"));

                    b.Property<int>("VehicleColorCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("VehicleColorHexadecimal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleColorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VehicleColorId");

                    b.HasIndex("VehicleColorCategoryId");

                    b.ToTable("VehicleColors");
                });

            modelBuilder.Entity("ToyotaMarketplace.Models.Vehicles.VehicleColorCategory", b =>
                {
                    b.Property<int>("VehicleColorCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleColorCategoryId"));

                    b.Property<string>("VehicleColorCategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VehicleColorCategoryId");

                    b.ToTable("VehicleColorCategories");
                });

            modelBuilder.Entity("ToyotaMarketplace.Models.Vehicles.VehicleModel", b =>
                {
                    b.Property<int>("VehicleModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleModelId"));

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VehicleTypeId")
                        .HasColumnType("int");

                    b.HasKey("VehicleModelId");

                    b.HasIndex("VehicleTypeId");

                    b.ToTable("VehicleModels");
                });

            modelBuilder.Entity("ToyotaMarketplace.Models.Vehicles.VehicleType", b =>
                {
                    b.Property<int>("VehicleTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleTypeId"));

                    b.Property<string>("VehicleTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Wheel")
                        .HasColumnType("int");

                    b.HasKey("VehicleTypeId");

                    b.ToTable("VehicleTypes");
                });

            modelBuilder.Entity("ToyotaMarketplace.Models.Users.ToyotaAdmin", b =>
                {
                    b.HasOne("ToyotaMarketplace.Models.Users.User", "User")
                        .WithOne("ToyotaAdmin")
                        .HasForeignKey("ToyotaMarketplace.Models.Users.ToyotaAdmin", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ToyotaMarketplace.Models.Vehicles.Specs.VehicleDimensionFuel", b =>
                {
                    b.HasOne("ToyotaMarketplace.Models.Vehicles.Specs.VehicleSpec", "VehicleSpec")
                        .WithOne("VehicleDimensionFuel")
                        .HasForeignKey("ToyotaMarketplace.Models.Vehicles.Specs.VehicleDimensionFuel", "DimensionFuelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VehicleSpec");
                });

            modelBuilder.Entity("ToyotaMarketplace.Models.Vehicles.Specs.VehicleFeature", b =>
                {
                    b.HasOne("ToyotaMarketplace.Models.Vehicles.Specs.VehicleSpec", "VehicleSpec")
                        .WithOne("VehicleFeature")
                        .HasForeignKey("ToyotaMarketplace.Models.Vehicles.Specs.VehicleFeature", "FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VehicleSpec");
                });

            modelBuilder.Entity("ToyotaMarketplace.Models.Vehicles.Specs.VehiclePerformance", b =>
                {
                    b.HasOne("ToyotaMarketplace.Models.Vehicles.Specs.VehicleSpec", "VehicleSpec")
                        .WithOne("VehiclePerformance")
                        .HasForeignKey("ToyotaMarketplace.Models.Vehicles.Specs.VehiclePerformance", "PerformanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ToyotaMarketplace.Models.Vehicles.Specs.TransmissionType", "TransmissionType")
                        .WithMany()
                        .HasForeignKey("TransmissionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TransmissionType");

                    b.Navigation("VehicleSpec");
                });

            modelBuilder.Entity("ToyotaMarketplace.Models.Vehicles.Specs.VehiclePerformanceDriveMode", b =>
                {
                    b.HasOne("ToyotaMarketplace.Models.Vehicles.Specs.DriveMode", "DriveMode")
                        .WithMany("VehiclePerformanceDriveModes")
                        .HasForeignKey("DriveModeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToyotaMarketplace.Models.Vehicles.Specs.VehiclePerformance", "VehiclePerformance")
                        .WithMany("VehiclePerformanceDriveModes")
                        .HasForeignKey("PerformanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DriveMode");

                    b.Navigation("VehiclePerformance");
                });

            modelBuilder.Entity("ToyotaMarketplace.Models.Vehicles.Specs.VehicleSpec", b =>
                {
                    b.HasOne("ToyotaMarketplace.Models.Vehicles.Vehicle", "Vehicle")
                        .WithOne("VehicleSpec")
                        .HasForeignKey("ToyotaMarketplace.Models.Vehicles.Specs.VehicleSpec", "VehicleSpecId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("ToyotaMarketplace.Models.Vehicles.Specs.VehicleTechnical", b =>
                {
                    b.HasOne("ToyotaMarketplace.Models.Vehicles.Specs.BrakeType", "BrakeType")
                        .WithMany("VehicleTechnicals")
                        .HasForeignKey("BrakeTypeId");

                    b.HasOne("ToyotaMarketplace.Models.Vehicles.Specs.FuelType", "FuelType")
                        .WithMany("VehicleTechnicals")
                        .HasForeignKey("FuelTypeId");

                    b.HasOne("ToyotaMarketplace.Models.Vehicles.Specs.PowerSteeringType", "PowerSteeringType")
                        .WithMany("VehicleTechnicals")
                        .HasForeignKey("PowerSteeringTypeId");

                    b.HasOne("ToyotaMarketplace.Models.Vehicles.Specs.SteeringSystem", "SteeringSystem")
                        .WithMany("VehicleTechnicals")
                        .HasForeignKey("SteeringSystemId");

                    b.HasOne("ToyotaMarketplace.Models.Vehicles.Specs.SteeringType", "SteeringType")
                        .WithMany("VehicleTechnicals")
                        .HasForeignKey("SteeringTypeId");

                    b.HasOne("ToyotaMarketplace.Models.Vehicles.Specs.BatteryType", "BatteryType")
                        .WithMany("VehicleTechnicals")
                        .HasForeignKey("TechnicalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToyotaMarketplace.Models.Vehicles.Specs.VehicleSpec", "VehicleSpec")
                        .WithOne("VehicleTechnical")
                        .HasForeignKey("ToyotaMarketplace.Models.Vehicles.Specs.VehicleTechnical", "TechnicalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BatteryType");

                    b.Navigation("BrakeType");

                    b.Navigation("FuelType");

                    b.Navigation("PowerSteeringType");

                    b.Navigation("SteeringSystem");

                    b.Navigation("SteeringType");

                    b.Navigation("VehicleSpec");
                });

            modelBuilder.Entity("ToyotaMarketplace.Models.Vehicles.Vehicle", b =>
                {
                    b.HasOne("ToyotaMarketplace.Models.Vehicles.Specs.PowerTrain", "PowerTrain")
                        .WithMany("Vehicles")
                        .HasForeignKey("PowerTrainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToyotaMarketplace.Models.Users.ToyotaAdmin", "ToyotaAdmin")
                        .WithMany("Vehicles")
                        .HasForeignKey("ToyotaAdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToyotaMarketplace.Models.Vehicles.VehicleColor", "VehicleColor")
                        .WithMany("Vehicles")
                        .HasForeignKey("VehicleColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToyotaMarketplace.Models.Vehicles.VehicleModel", "VehicleModel")
                        .WithMany("Vehicles")
                        .HasForeignKey("VehicleModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PowerTrain");

                    b.Navigation("ToyotaAdmin");

                    b.Navigation("VehicleColor");

                    b.Navigation("VehicleModel");
                });

            modelBuilder.Entity("ToyotaMarketplace.Models.Vehicles.VehicleColor", b =>
                {
                    b.HasOne("ToyotaMarketplace.Models.Vehicles.VehicleColorCategory", "VehicleColorCategory")
                        .WithMany("VehicleColors")
                        .HasForeignKey("VehicleColorCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VehicleColorCategory");
                });

            modelBuilder.Entity("ToyotaMarketplace.Models.Vehicles.VehicleModel", b =>
                {
                    b.HasOne("ToyotaMarketplace.Models.Vehicles.VehicleType", "VehicleType")
                        .WithMany("VehicleModels")
                        .HasForeignKey("VehicleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("ToyotaMarketplace.Models.Users.ToyotaAdmin", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("ToyotaMarketplace.Models.Users.User", b =>
                {
                    b.Navigation("ToyotaAdmin")
                        .IsRequired();
                });

            modelBuilder.Entity("ToyotaMarketplace.Models.Vehicles.Specs.BatteryType", b =>
                {
                    b.Navigation("VehicleTechnicals");
                });

            modelBuilder.Entity("ToyotaMarketplace.Models.Vehicles.Specs.BrakeType", b =>
                {
                    b.Navigation("VehicleTechnicals");
                });

            modelBuilder.Entity("ToyotaMarketplace.Models.Vehicles.Specs.DriveMode", b =>
                {
                    b.Navigation("VehiclePerformanceDriveModes");
                });

            modelBuilder.Entity("ToyotaMarketplace.Models.Vehicles.Specs.FuelType", b =>
                {
                    b.Navigation("VehicleTechnicals");
                });

            modelBuilder.Entity("ToyotaMarketplace.Models.Vehicles.Specs.PowerSteeringType", b =>
                {
                    b.Navigation("VehicleTechnicals");
                });

            modelBuilder.Entity("ToyotaMarketplace.Models.Vehicles.Specs.PowerTrain", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("ToyotaMarketplace.Models.Vehicles.Specs.SteeringSystem", b =>
                {
                    b.Navigation("VehicleTechnicals");
                });

            modelBuilder.Entity("ToyotaMarketplace.Models.Vehicles.Specs.SteeringType", b =>
                {
                    b.Navigation("VehicleTechnicals");
                });

            modelBuilder.Entity("ToyotaMarketplace.Models.Vehicles.Specs.VehiclePerformance", b =>
                {
                    b.Navigation("VehiclePerformanceDriveModes");
                });

            modelBuilder.Entity("ToyotaMarketplace.Models.Vehicles.Specs.VehicleSpec", b =>
                {
                    b.Navigation("VehicleDimensionFuel")
                        .IsRequired();

                    b.Navigation("VehicleFeature")
                        .IsRequired();

                    b.Navigation("VehiclePerformance")
                        .IsRequired();

                    b.Navigation("VehicleTechnical")
                        .IsRequired();
                });

            modelBuilder.Entity("ToyotaMarketplace.Models.Vehicles.Vehicle", b =>
                {
                    b.Navigation("VehicleSpec")
                        .IsRequired();
                });

            modelBuilder.Entity("ToyotaMarketplace.Models.Vehicles.VehicleColor", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("ToyotaMarketplace.Models.Vehicles.VehicleColorCategory", b =>
                {
                    b.Navigation("VehicleColors");
                });

            modelBuilder.Entity("ToyotaMarketplace.Models.Vehicles.VehicleModel", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("ToyotaMarketplace.Models.Vehicles.VehicleType", b =>
                {
                    b.Navigation("VehicleModels");
                });
#pragma warning restore 612, 618
        }
    }
}
