// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToyotaMarketplace.Areas.Data;

#nullable disable

namespace ToyotaMarketplace.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260428113421_AddElectricHybridFieldsInVehicleTable")]
    partial class AddElectricHybridFieldsInVehicleTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ToyotaMarketplace.Models.Users.ToyotaAdmin", b =>
                {
                    b.Property<int>("ToyotaAdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ToyotaAdminId"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ToyotaAdminId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ToyotaAdmins");
                });

            modelBuilder.Entity("ToyotaMarketplace.Models.Users.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserFirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ToyotaMarketplace.Models.Vehicles.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleId"));

                    b.Property<bool>("IsElectric")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHybrid")
                        .HasColumnType("bit");

                    b.Property<int>("ToyotaAdminId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleColorId")
                        .HasColumnType("int");

                    b.Property<string>("VehicleImg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VehicleModelId")
                        .HasColumnType("int");

                    b.Property<string>("VehicleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VehicleSRP")
                        .HasColumnType("int");

                    b.HasKey("VehicleId");

                    b.HasIndex("ToyotaAdminId");

                    b.HasIndex("VehicleColorId");

                    b.HasIndex("VehicleModelId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("ToyotaMarketplace.Models.Vehicles.VehicleColor", b =>
                {
                    b.Property<int>("VehicleColorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleColorId"));

                    b.Property<string>("VehicleColorHexadecimal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleColorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VehicleColorId");

                    b.ToTable("VehicleColors");
                });

            modelBuilder.Entity("ToyotaMarketplace.Models.Vehicles.VehicleModel", b =>
                {
                    b.Property<int>("VehicleModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleModelId"));

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VehicleTypeId")
                        .HasColumnType("int");

                    b.HasKey("VehicleModelId");

                    b.HasIndex("VehicleTypeId");

                    b.ToTable("VehicleModels");
                });

            modelBuilder.Entity("ToyotaMarketplace.Models.Vehicles.VehicleType", b =>
                {
                    b.Property<int>("VehicleTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleTypeId"));

                    b.Property<string>("VehicleTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Wheel")
                        .HasColumnType("int");

                    b.HasKey("VehicleTypeId");

                    b.ToTable("VehicleTypes");
                });

            modelBuilder.Entity("ToyotaMarketplace.Models.Users.ToyotaAdmin", b =>
                {
                    b.HasOne("ToyotaMarketplace.Models.Users.User", "User")
                        .WithOne("ToyotaAdmin")
                        .HasForeignKey("ToyotaMarketplace.Models.Users.ToyotaAdmin", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ToyotaMarketplace.Models.Vehicles.Vehicle", b =>
                {
                    b.HasOne("ToyotaMarketplace.Models.Users.ToyotaAdmin", "ToyotaAdmin")
                        .WithMany("Vehicles")
                        .HasForeignKey("ToyotaAdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToyotaMarketplace.Models.Vehicles.VehicleColor", "VehicleColor")
                        .WithMany("Vehicles")
                        .HasForeignKey("VehicleColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToyotaMarketplace.Models.Vehicles.VehicleModel", "VehicleModel")
                        .WithMany("Vehicles")
                        .HasForeignKey("VehicleModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ToyotaAdmin");

                    b.Navigation("VehicleColor");

                    b.Navigation("VehicleModel");
                });

            modelBuilder.Entity("ToyotaMarketplace.Models.Vehicles.VehicleModel", b =>
                {
                    b.HasOne("ToyotaMarketplace.Models.Vehicles.VehicleType", "VehicleType")
                        .WithMany("VehicleModels")
                        .HasForeignKey("VehicleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("ToyotaMarketplace.Models.Users.ToyotaAdmin", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("ToyotaMarketplace.Models.Users.User", b =>
                {
                    b.Navigation("ToyotaAdmin")
                        .IsRequired();
                });

            modelBuilder.Entity("ToyotaMarketplace.Models.Vehicles.VehicleColor", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("ToyotaMarketplace.Models.Vehicles.VehicleModel", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("ToyotaMarketplace.Models.Vehicles.VehicleType", b =>
                {
                    b.Navigation("VehicleModels");
                });
#pragma warning restore 612, 618
        }
    }
}
